### PR TITLE
sasl support

### PR DESCRIPTION
**Pull request by flyinprogrammer**
this is terrible code but it works lolz feel free to suggest how I might make this better.

### CODE REVIEW

**Comment by williamboman** [comment]
Nice! Right of the bat I noticed there's a lot of code style (semantic) changes - these should not be a part of this PR (not only do they make reviewing a PITA, it has nothing to do with implementing SASL support). Also, additions to `.gitignore` that targets specific editor/IDE junk should be removed, store them in your global, personal `.gitignore` instead.

**Comment by flyinprogrammer** [comment]
alright so now the PR should only show 'real' code changes

**Comment by williamboman** [comment]
I managed to trim some more cosmetic changes to make this easier to review.

```sh
$ git fetch git@github.com:williamboman/slate-irc feat/sasl-support && git merge --ff-only FETCH_HEAD
```

**Comment by flyinprogrammer** [comment]
thanks dude :+1:  we should probably get some eslint up in this project through - there are definitely a lot of things worth correcting.

**Pull request closed without merging**
